ssl-hep/ServiceX_frontend

- README.md
- servicex/servicex.py
- tests/test_servicex.py
A physicist would like some control over how many resources are used by `servicex` (until auto-scaling is present). This gives the user access to the number of transformers that will run simultaneously.
- This PR adds the parameter `max_workers` to `get_data` and `get_data_async`, which allow the user to control the number of workers used by ServiceX (see issue #17 ). The amount of code changed is actually quite small.
- @kyungeonchoi - I've put you on review here to make sure you are happy with the interface.
- @BenGalewsky and @mweinberg2718 - I've put you on the review to make sure the text I'm using to describe `max_workers` is ok. Right now, without autoscaling, `max_workers` is really the number of workers, but eventually, it will either be removed, or it will be an upper limit. If …
> Add a max_workers parameter to get_data and get_data_async

- README.md
- servicex/servicex.py
- tests/test_servicex.py
This library has not, up to this point, supported downloading files from `servicex` and returning them to the user. There are now several people who are using this feature ad-hoc. This PR:
- File downloads (see issue #8 for details)
- Support Parquet files (see issue #7 for details)
- Always return the same event ordering (see issue #14 for details).
The library already does this asynchronously. This PR exposes that to the user, and then adds a few small features onto that (like sorting and parquet files).
- @kyungeonchoi - I assume this is all that you need - just pass in a new file type (search the changed files tab for `parquet`.
- @BenGalewsky and @mweinberg2718 - There is a lot in here, sorry! I guess sorting by filename to maintain order (see slack convo), and also anything generic …
> Support File Downloads

- .github/workflows/ci.yaml
- .vscode/settings.json
- servicex/.flake8
- servicex/__init__.py
- servicex/servicex.py
- servicex/utils.py
- setup.py
- tests/.flake8
- tests/test_servicex.py
- tests/test_utils.py
- tests/utils_for_testing.py
This makes caching available to the end-user when working with Service. The goals are:
- If the same query is made to ServiceX, that the data are not re-downloaded. This is across program restarts
- Within the same execution environment, if the data has been loaded once, it should not be reloaded (assumes data is immutable).
WIP
> WIP: Data and File Caching

- .vscode/settings.json
- servicex/servicex.py
- servicex/servicex_adaptor.py
- tests/conftest.py
- tests/test_servicex.py
- tests/test_servicex_adaptor.py
- Ability to bring back transform errors by querying ServiceX
- Errors are dumpped to the logger, at the `warning` level.
- If any files fail to transform, all transform errors are dumpped locally
Fixes #67
> Print out container errors during failed transformations

- .vscode/settings.json
- servicex/__init__.py
- servicex/servicex.py
- servicex/servicex_adaptor.py
- servicex/utils.py
- tests/conftest.py
- tests/test_servicex.py
- tests/test_servicex_adaptor.py
- If status: Fatal comes back from a /status query, throw an exception
- Grab data from the transform get endpoint to get the full error text and include it in the exception for the user.
Fixes #30
> Detect transformation Fatal Status and report to user (#30)

- .vscode/settings.json
- README.md
- servicex/__init__.py
- servicex/cache.py
- servicex/config_default.yaml
- servicex/minio_adaptor.py
- servicex/servicex.py
- servicex/servicex_adaptor.py
- servicex/utils.py
- setup.py
- tests/conftest.py
- tests/test_cache.py
- tests/test_minio_adaptor.py
- tests/test_servicex.py
- tests/test_servicex_adaptor.py
RC2 of ServiceX released a bunch of features. This PR adds features to make them accessible to the user:
- #79 - Fetches the /transformation endpoint data
- #80 - Uses minio auth information from the /transformation endpoint data
- #82 - When a file fails to transform, dump transform logs of failed pods to the logger.warning.
- #30 - If the DID look up fails (or simlar error), report error message to use from /transform status
- ServiceX_App/34 - The ServiceX app now uses email/password to authenticate.
Goal would be to merge this along with other changes into master as version 1.1 once approved.
> Bring ServiceX Frontend inline with ServiceX 1.0 RC2

- servicex/data_conversions.py
- tests/conftest.py
- tests/test_data_conversions.py
- tests/test_servicex.py
These changes will update the awkward data converter. It will now convert data to `LazyArray` objects. This change also updates the data_conversion tests to reflect that a `LazyArray` is a different type of object from the previous `Array` dictionaries.
> update to change awkward arrays to load lazily

- .vscode/settings.json
- README.md
- servicex/__init__.py
- servicex/cache.py
- servicex/servicex.py
- tests/test_cache.py
- tests/test_servicex.py
This code adds a context manager that, while in effect, will prevent queires from being found in the cache when they are initiated.
Fixes #44
> Add ability to ignore the local cache

- servicex/servicex.py
- servicex/servicex_config.py
- servicex/servicexabc.py
- tests/test_servicex.py
- Make sure the image name is None by default
- Do not include an "image" tag in the API request if we don't need it.
- Fix up some flake8 errors
Fixes #123
> Allow image to be "none"

- servicex/cache.py
- tests/test_cache.py
CMS NanoAOD files can wind up with really long names. This causes errors when they are downloaded from Minio.
This is solution to #128 
* Establish a `MAX_PATH_LEN`
* In the Minio adaptor truncate the filename from the left to keep (when combined with the parent path) within the limit.
This assumes that for a dataset, the rightmost characters are most unique.
> Truncate filenames to avoid ones that are too long

- servicex/servicex.py
- tests/test_servicex.py
- The final status update was done no matter the state of the local cache - this call is now protected.
- Test was not good enough to catch this - that was also improved.
> Cached queries should not talk to the internet

- README.md
- servicex/ConfigSettings.py
- tests/test_ConfigSettings.py
The locations that a .servicex or servicex.yaml file can be found are now:
- Your current working directory
- Any directory above your current working directory**
- Your home directory
** Added by this MR.
This MR also adds a test to make sure that a config file in yoru current working directory takes precedence over something found in your home directory.
Fixes #65
Fixes #63
> Look at parent directories for configuration file

- README.md
- servicex/servicex.py
- servicex/servicex_config.py
- tests/test_servicex_config.py
We now use `servicex.yaml`, `servicex.yml`, and `.servicex` files for configuration. The documentation and code comments hadn't quite caught up with that. This should take care of that.
Fixes #155
> Fix up references to .servicex files in documentation and comments

- servicex/servicex.py
- servicex/utils.py
- tests/test_servicex.py
This will automatically retry the query when:
- We have cached the query locally
- We have not cached the data files locally
- The backend servicex system does not know about the query (so we can't re-fetch the data).
This happens when servicex is restarted.
Fixes #146
> Retry when a query miss occurs

- README.md
- servicex/config_default.yaml
- servicex/utils.py
- tests/test_utils.py
- The default cache location on linux is now `/tmp/servicex_<user>`, and on windows similar, but in the `TEMP` directory (which is already per-user).
- Also updated the docs to note that on linux the `/etc/servicex` directory is searched for a file since the `confuse` python config library is getting used.
Fixes #147
> Default data cache location is per-user

- servicex/servicex.py
- tests/test_servicex.py
If we switch from `stream_result_file_urls` to `stream_result_files` in the Local executor, we want the interface to the returned objects to be the same
Fixes #161 
Added URL property to StreamInfoPath that returns a `file://` URI to the downloaded file
> Add URL property to StreamInfoPath

- servicex/cache.py
This will make sure filenames that are too long for the local filesystem just truncated, but also hashed so there will be very little chance of collisions.
Ths is fixing some technical debt.
Fixes #169
> Hash long filenames

- servicex/servicex.py
- tests/test_servicex.py
Fixes #180
* Adds the method `first_supported_datatype`. Given a list of data formats your app supports, it will return the first one that this servicex instance can return
> Probe for viable data return formats

- .vscode/settings.json
- README.md
- servicex/servicex.py
- servicex/servicexabc.py
- tests/test_servicex.py
Completes work on https://github.com/ssl-hep/ServiceX/issues/269 - which added the title to the backend.
* The title is passed in as an optional argument to any of the `get_xxxx` calls
* By default no title is passed - and ServiceX will call the request "Untitled".
Fixes #163
> Support passing an optional request title

- .vscode/settings.json
- README.md
- servicex/__init__.py
- servicex/cache.py
- servicex/data_conversions.py
- servicex/servicex.py
- servicex/servicex_config.py
- servicex/servicexabc.py
- servicex/utils.py
- tests/test_cache.py
- tests/test_servicex.py
- tests/test_servicex_adaptor.py
- tests/test_servicex_config.py
- tests/test_utils.py
Fixes #170
Support lists of files as a dataset name. This will allow randomly located files to be sent to ServiceX for processing.
> Support lists of files rather than just datasets

- README.md
- servicex/servicex.py
- servicex/utils.py
- tests/test_servicex.py
Fixes #178
* You can use `http://` or `root://` as a dataset identifier and it will process a single file
* Updated documentation to specify how to access data.
> Allow single http/root as a input data

- servicex/__init__.py
Fixes #179
* Make it easy to import StreamInfoPath, not just StreamInfoUrl.
> Export StreamInfoPath from the root __init__ file

- README.md
- servicex/cache.py
- servicex/servicex.py
- tests/conftest.py
- tests/test_cache.py
- tests/test_servicex.py
Query cache status files can now be deleted by the user (or some other agent):
* Recover if the status is missing by re-querying the backend
* Add documentation to talk a little bit about how the cache works
Fixes #176
> Support Missing Query Cache Status Files

- .vscode/tasks.json
- README.md
- servicex/cache.py
- servicex/minio_adaptor.py
- servicex/servicex.py
- servicex/servicex_adaptor.py
- servicex/utils.py
- setup.py
- tests/conftest.py
- tests/test_cache.py
- tests/test_servicex.py
- tests/test_utils.py
* If SX knows about the transform, but minio does not, trigger new request
* If the streaming url hits an exception before getting any files, enable a new request
* If there is a fatal transform error, keep cache empty so it can be easily re-run
* If the user deletes a data file from the cache, automatically re-download it.
* When a lot of errors come back from ServiceX, only dump the first 20
* Added info logging messages to help track when we are downloading files
The second was actually supposed to have been working previously, but due to how async iterators work, it was not.
Fixes #86
Fixes #189
Fixes #193 
Fixes #188
Works on #187
> Backend Download and Query Cache Updates

- README.md
- scripts/run_test.py
- servicex/config_default.yaml
- servicex/servicex.py
- servicex/servicex_config.py
- tests/test_servicex_config.py
Will now look for a name in the `api_endpoint` rather than just a `type` when doing the lookup.
Fixes #194
> Better management of endpoints and types

- .github/workflows/ci.yaml
- README.md
- servicex/__init__.py
- servicex/cache.py
- servicex/servicex.py
- servicex/servicex_config.py
- tests/test_cache.py
- tests/test_servicex_config.py
* If there is an analysis cache json file present, include it in the query cache resolution.
* Make it possible to write out an analysis cache automatically while running
* Remove bad queries automatically from an analysis cache
* Makes it possible to distribute the same data used by multiple poeple, easily.
* flake8 now runs initially in the CI, and then everything else runs
* Update documentation
* Make for a hard crash when we ask for a backend by name and we don't know about it. This is to help avoid accidentally marking analysis cache entries bad.
Fixes #172
> Implement an Analysis Cache

- .vscode/tasks.json
- servicex/servicex_config.py
- tests/test_servicex_config.py
* Bug fix: was not fetching the return datatype correctly. But was introduced in one of the previous updates for this version.
Revamped the whole default attributes per end point resolution into a single much more coherrent method. All the logic is now in one place!
> Fix backend default datatype resoluiton

- servicex/utils.py
* `title` of a transform should not affect its hash calculation!
> Ignore the title when calculating the hash

- README.md
- servicex/servicex.py
- servicex/servicexabc.py
It is not possible to specify the `result-destination` for ServiceX Submits. It always defaults to `object-store`
Solution to #215 
Added a new argument to the ServiceX constructor. Use this in the invocation of ServiceX Transform
> Add optional constructor to change the result-destination

- .github/workflows/ci.yaml
GitHub Actions has dropped the VM for python 3.6 - tests are failing
Removed 3.6 from the test matrix
> Drop python 3.6 from test matrix

- .github/workflows/ci.yaml
- pytest.ini
- servicex/servicex.py
- servicex/servicex_utils.py
- tests/test_servicex.py
* Currently in-memory cache was using only a hash calculated from the query and the dataset. That missed the fact that the same query can render awkward arrays and root files. This fixes that!
* Rationalize how we are running `pytest`
* Minor text clean up
Fixes #42
> In Memory Cache - Include Datatype

- servicex/utils.py
- setup.py
`backoff` bumpped to version 2.0
* We are using some of its internal code to emulate what we've got. This broke.
> Run with the new version of backoff

- setup.py
The specific version doesn't seem to be required and is causing a downstream conflict with Cachetools library
> Unpin google-auth library

- servicex/minio_adaptor.py
- servicex/servicex.py
- tests/test_minio_adaptor.py
- tests/test_servicex.py
The latest version of _coffea_ `NanoEvents` can no longer read parquet files supplied via http.
Solution to #238 
1. Changed the names of the get data url stream methods to be uri_stream to be more accurate
2. Added an optional parameter to the methods `as_signed_url` - by default this is False, but if you set it to True you can still get back the signed urls. Otherwise you get back s3 URIs
> Add as_signed_url property so url_streams can return s3 URIs by default

- .github/workflows/ci.yaml
- scripts/run_test.py
- servicex/servicex.py
- tests/test_servicex.py
* Implemented new functions to synchronously get all URLs from a request, for ROOT files and Parquet files. 
Functions are implemented as async to create the lists of URLs and then made sync after. Tests for each new function are also added.
* Fixed long-standing protection against `flake8` running during the initial stages (and got it back to passing flake8!!).
> Added functions to get URLs sync from request + corresponding tests

- .vscode/settings.json
- servicex/servicex.py
Bug fixes:
* Make sure to be consistent about passing `root-file` and not `root-files`
* Limit the result format types allowed to `root-file` and `parquet`. There is a global var in `servicex.py` that contains the legal list that can be updated when testing new formats.
* Change where `flake8` in `vscode` gets its info from
Fixes #253
> Do not request `parquet` when we want `root-file`

- servicex/servicex.py
- servicex/servicexabc.py
- servicex/utils.py
- tests/conftest.py
- tests/test_servicex.py
* Fix #259 - get_awkward now properly requests parquet files from an uproot background, and root files from a xaod backend.
* get_pandas does the same things
* Spell checker was run on multiple source files and spelling updated.
* A global variable in `servicex.py` limits you to what data formats you can request. It is now possible to alter that global variable if you want to add a new format without having to `hack` the package.
> Obey default data return formats

- .github/workflows/ci.yaml
- servicex/config_default.yaml
- setup.py
* Update `setup`'s restrictions to remove upper limits on things like `quastle`.
* Make sure there is a default `uproot`-backend definition in the default fall-back `servicex.yaml` file.
* Relax the `make_async` package restriction
* Relax the `confuse` yaml parser definition
* Add mac-os testing in (not sure why it wasn't there!)
* And have it run its periodic checks once per week, not once per day.
Working towards a 2.6.2 release.
> Update changes for release

- servicex_client/minio_adapter.py
- tests/test_minio_adapter.py
Make sure that filenames for files coming back from minio have ":", "*", etc., removed so they are safe on any OS
> Safe Downloaded Filenames

- servicex_client/minio_adapter.py
- tests/test_minio_adapter.py
* Fixed bug in short-filename logic
* The max filename should never be shorter than the hash length, or the result is undefiend.
* Changed filename length to be 60.
> Short Filenames

- servicex/configuration.py
Small changes to configuration.py to search for both .servicex and servicex.yaml config files, while also accepting a user-defined config file path.
> Accept both .servicex and servicex.yaml config files

- servicex/configuration.py
When trying to read config from a path, if that path is not found we get an unrelated error about alt_name
> Correctly report not being able to find config file from path

- servicex/configuration.py
- tests/example_config_no_cache_path.yaml
- tests/test_config.py
There is no default for cache_path if not provided in the .servicex file. The error messages are unclear as well.
We also want to support expanding ${USER} in the path to make it easy to support multiple users on a single JupyterHub node
Fixes #297
> Handle missing cache_dir and expand bengal1 in path

- servicex/func_adl/func_adl_dataset.py
There is no way to specify which tree you want an uproot transformer to operate on
The tree name needs to be appended to the first `Call` in the AST. It has to be appended along with a filename (which doesn't seem to be used anywhere).
The set_tree operation needs to clone the AST so you can do something like:
```python
q = ds.Select(lambda e: {'el_pt': e['el_pt']})\
.set_result_format(ResultFormat.parquet)
nominal = q.set_tree("nominal")
mmt_2016 = q.set_tree("mmt_2016")
print(nominal.as_files())
print(mmt_201.as_files())
```
Cloning the AST was a bit tricky since there is a reference to the FuncADLDataset in a private property, `_eds_object`. 
I wrote a custom `__deepcopy__` method to carefully avoid cloning the open file pointer to the cache DB.
I don't think anyone uses `_eds_object` …
> Set Tree Operation

- servicex/dataset.py
I can set the title of a transform request at constructor time, however if I want to chain selects together and give each clone its own title I can't do it
> Add operation to set the title of a dataset

- README.md
- servicex/data_conversions.py
- setup.py
- tests/test_data_conversions.py
Enable awkward 2.0 support in `servicex`
* Setup configured to support only awkward 1.0 if you are on python 3.7 (we need to drop support for this!)
* If you load a `awkward` array using this library, it will give you an `awkward_dask` array if `awkward` 2.0 is loaded, or a `lazy` array if `awkward` 1.0 is in your environment.
Fixes #316
> Awkward 2.0 support in `servicex` 2.0

- servicex/servicex_adaptor.py
- tests/test_servicex_adaptor.py
ServiceX no longer returns a *Fatal* error when it is asked to look up a bad dataset name or a dataset name that has zero files.
* Detect a completed transform with no files
Fixes #313
Fixes #312
> Deal with empty and bad dataset names

- servicex/models.py
- tests/conftest.py
- tests/test_datest_group.py
- tests/test_query_cache.py
The `ResultFormat` for root is named differently from the one for parquet
Fixes #320 
Changed the type to be just plain `root`
> Change name of root-file result format

- .vscode/settings.json
- servicex/config_default.yaml
- servicex/data_conversions.py
- servicex/servicex.py
- servicex/servicex_config.py
- tests/test_servicex.py
* New version of uproot/awkward returns the version number for tree keys - but can't handle them in an `uproot.open`. Strip off the version number if it is there.
* Classic example of VMS living on!
* Revise default configuration for backend name to reflect how ServiceX is usually configured, moving from `atlasxaod` to `atlasr21`.
Fixes #326
> Safeguard against VMS version numbers in tree names returned by `uproot`

- servicex/models.py
- tests/test_servicex_adapter.py
For consistency sake, the enum was changed to root, however this is not what the server expects. To fix this we keep the enum key root, but make the string representation root-file. Added a unit test to verify this along with a pointer to the statement in the ServiceX client which sets up the valid values for this field
> Match the root file result format in the generated json to the expected value in the service

- servicex/models.py
The `workflow` property of the transform request is no longer used. This PR removes it from the model so that we can work with versions of ServiceX that no longer include it in the response.
> Ignore workflow property in transform request object

- .github/workflows/ci.yaml
- servicex/data_conversions.py
- tests/test_data_conversions.py
* Added test that will try to open a file `simple.root.1:treeme`.
ToDo:
Fixes #337
> Open with post-fix filename fails

- servicex/databinder_models.py
In the `ServiceXSpec` model in `databinder_models.py`, the function `replace_definition` has a check to see if the `Definition` key exists in the `values` dictionary. However, running the bigger_uproot.py I noticed that key had a value None and this was not checked and was throwing an AttributeError.
Added another condition to check for None value for the key `Definition`.
> None value check for Definition key 

- servicex/configuration.py
- tests/test_config.py
When user does not give `cache_path` in `.servicex`, the default temp directory is used. Therefore when you try to clear the cache, some files are not deleted due to permission issue.
Rather than having `/tmp` as the default added `/tmp/servicex_$USER`. 
This ensures the local cache is set to this path and it is safely deleted when clearing cache
In the configuration.py-> `expand_cache_path(cls, v)`, changed the default value of `v="/tmp"` to `v="/tmp/servicex_$USER"`
Added tests for this new changes in test_config.py
> Cache Clear fix on Temp files not deleting

- examples/bigger_uproot.py
- examples/config_databinder_func_adl.yaml
- examples/config_databinder_python.yaml
- examples/databinder.py
- examples/python_codegen.py
- examples/single_file_uproot.py
- poetry.lock
- servicex/__init__.py
- servicex/configuration.py
- servicex/databinder_models.py
- servicex/dataset_group.py
- servicex/func_adl/func_adl_dataset.py
- servicex/python_dataset.py
- servicex/query.py
- servicex/servicex_client.py
- tests/conftest.py
- tests/test_config.py
- tests/test_dataset.py
- tests/test_python_dataset.py
- tests/test_servicex_dataset.py
After extensive testing with the 3.0 api, users have suggested moving to a fully declarative api, based on DataBinder.
In this PR, we moved Databinder classes to pydantic
> Databindereatstheworld

- pyproject.toml
* Add missing CLI API entrypoint.
* Amends PR #349.
> fix: Add CLI entrypoint

- .github/workflows/pypi.yaml
* Use the OpenID Connect (OIDC) standard to publish to PyPI using PyPI's "Trusted Publisher" implementation to publish without using API tokens stored as GitHub Actions secrets.
- c.f. https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/
- c.f. https://docs.pypi.org/trusted-publishers/
For a full example (with lots of discussion) c.f. https://github.com/scikit-hep/pyhf/pull/2183
For a concise summary, c.f. the [Scientific Python Developer Guide section on this](https://learn.scientific-python.org/development/guides/gha-wheels/#publishing).
1. Login to PyPI
2. Follow the [Adding a trusted publisher to an existing PyPI project](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) instructions.
> ci: Use trusted publishers for publishing to PyPI

- .github/workflows/ci.yaml
- .vscode/settings.json
- setup.py
* Remove the upper bound on the `pandas` installation.
* Remove 3.7 testing and support (`pandas` is no longer around for that release!).
* Fix up some config options we for vscode that are depreciated.
Fixes #357
> Remove pandas restrictions

- .github/workflows/ci.yaml
- examples/config_databinder_func_adl.yaml
- examples/config_databinder_python.yaml
- examples/python_codegen.py
- examples/stress_test.py
- servicex/databinder_models.py
- tests/test_databinder.py
The Pydantic 3.0 client doesn't accept multiple root file paths. It only supports a single root file. 
Changed the name of the property from `XRootdFile` to `XRootDFiles` and allow it to be a string or a list of strings. Note that the case changed on this too.
Need to start testing more of this functionality out, so I updated test_databinder as a start
> Multiple xrootdfiles

- .github/workflows/ci.yaml
- .github/workflows/pypi.yaml
* Use 'uv pip' for all calls to 'pip install' in GitHub Actions workflows.
- c.f. https://github.com/astral-sh/uv/
- In the case of the serviceX client, this is just a few seconds saved, but that adds up over every CI run.
* The '--system' call is required as uv requires a virtual environment to be activated without it, and GitHub Actions does not provide a default virtual environment.
> ci: Use uv for all pip installs

- servicex/app/transforms.py
- servicex/models.py
- servicex/query.py
- servicex/query_cache.py
- servicex/servicex_adapter.py
- tests/test_servicex_app_transforms.py
The users would like to know the title of transforms and not just the request ID. They would also like to be able to view the logs for a transform without having to navigate the dashboard
REST server nows sends the title over as well as the basic Logs url. Client will now parse this and use it in various places
> Process Transform Title and Log URL

- .vscode/settings.json
- servicex/servicex_adapter.py
The default transform submission timeout is 5 seconds. In cases where ServiceX has a very large cached filelist (say 65K!) it can take more than 5 seconds for it to reply.
This change makes the client more robust against that sitaution.
* Update old vscode settings
> Allow timeout for transform submission

- examples/bigger_uproot.py
- examples/databinder.py
- examples/single_file_uproot.py
- servicex/query.py
- servicex/servicex_client.py
This PR will exchange some of the `rich.print` calls that happen as the library runs and route them through `logging.info` and `logging.warning` and `logging.error`.
* Less inline output while library is running
* Allows user of library to control how much output is printed
* Brings it into line for the "correct" way to use library, according to python.
> Use logging library for status updates

- servicex/servicex_adapter.py
Be more informative if e.g. status 500 is returned from ServiceX
> Handle unknown status code being returned in submission

- servicex/servicex_adapter.py
When ServiceX gets busy, sometimes it takes a little longer than 5 seconds (5.1 seconds in testing) to respond to a status transfer. This change will make sure we don't fail when that happens.
Fixes #373.
> Add timeout to transform status

- servicex/servicex_adapter.py
If ServiceX responds with a > 400 error on the transform WebAPI, properly display the error message.
> Properly display error from transform

- servicex/servicex_adapter.py
PR #378 was working but not tuned up before the submission. This PR:
* Improves error logic (it wasn't wrong before, just two options for a branch)
* Improves the error message further.
Error message now looks like the following:
```
File "/venv/lib/python3.9/site-packages/servicex/dataset_group.py", line 76, in as_signed_urls_async
return await asyncio.gather(*self.tasks)
File "/venv/lib/python3.9/site-packages/servicex/query.py", line 521, in as_signed_urls_async
return await self.submit_and_download(
File "/venv/lib/python3.9/site-packages/servicex/query.py", line 260, in submit_and_download
self.request_id = await self.servicex.submit_transform(sx_request)
File "/venv/lib/python3.9/site-packages/servicex/servicex_adapter.py", line 120, in submit_transform
raise RuntimeError("ServiceX …
```
> Further clean up of error messages

- servicex/dataset_group.py
The default progress bar is set to `overall_progress` when `Delivery` is set to `SignedURLs`. Fix default to show progress bar for each sample.
> Fix default progress bar for SignedURL 

- servicex/databinder_models.py
- servicex/servicex_client.py
- tests/example_config_default_endpoint.yaml
- tests/test_databinder.py
- tests/test_default_endpoint.py
- `General.ServiceX` as an optional field to further minimize boilerplate
- Now `General` block can be omitted from `ServiceXSpec` and only `Sample` block is required
- Default `General.ServiceX` value is taken from the `default_endpoint` if present in the `servicex.yaml`. Otherwise the first endpoint is taken. (Assuming normal users have one endpoint)
> General.ServiceX as an optional field

- servicex/models.py
Fix accidental lowercase in the enum definition
> Fix status code enum

- pyproject.toml
https://coverage.readthedocs.io/en/latest/contexts.html
Dynamic Contexts - answers the question “what test ran this line?”
Steps to see the coverage report locally.
1. `coverage run -m pytest tests`
2. `coverage html --show-contexts`
> Coverage report to check the contexts under which the code was run

- .github/workflows/ci-production.yaml
This needs to be on the default branch (but also needs to point at the branch we want tested)
> Add 3.0_develop CI to master branch (as github demands)

- servicex/query_cache.py
- servicex/query_core.py
- tests/test_query_cache.py
- tests/test_servicex_dataset.py
A miniature variant of #318 : if there are any failures, don't store in the cache at all (as opposed to noting the failure in the cache). Also doesn't include the locking features of #318.
> Don't add failed results to cache

- examples/Uproot_FuncADL_Dict.py
- examples/Uproot_PythonFunction_Dict.py
- examples/Uproot_UprootRaw_Dict.py
- servicex/__init__.py
- tests/test_databinder.py
Remove many things from the top-level `servicex` namespace. What remains:
```
__all__ = [
"ResultFormat",
"ResultDestination",
"Sample",
"General",
"ServiceXSpec",
"deliver",
"dataset",
"query"
]
```
> Cleanup servicex namespace

- servicex/python_dataset.py
If source code was indented, it would previously fail with IndentationError. Fix by removing common indentation at the start of lines.
> Fix for function indentation in Python transformer

- servicex/query_core.py
This PR fixes disappearing sample title after transformation is completed. It's clear enough from the change of transformation progress bar and completed file counter.
Previously:
and with Fix:
> Fix disappearing sample title

- servicex/query_core.py
Added the request id in the logger when the request fails
Also changed the log level from warning to error
> Display the tranform request id on failure

- servicex/dataset_group.py
- servicex/servicex_client.py
- tests/conftest.py
- tests/test_databinder.py
- tests/test_dataset_group.py
- tests/test_guardlist.py
- tests/test_output_handler.py
By default, let `deliver()` return all requests made, even if some of them throw exceptions. Each return list is wrapped in a `GuardList` which will reraise any exception if the user attempts to access the corresponding result, and whose validity can be checked with `.valid()`.
> Use "guard list" for `deliver()`

- servicex/databinder_models.py
- tests/test_databinder.py
- Sample option `NFiles` is properly propagated for `RucioDID` but not for Rucio dataset defined via `Dataset`. e.g. `Dataset: servicex.dataset.Rucio("mc20_13TeV:EXAMPLE_DID")`
- This PR fixes this and includes a test
> Fix Sample option `NFiles` for Dataset

- servicex/databinder_models.py
- tests/test_databinder.py
- Truncate Sample name to 128 characters if length is longer than 128 characters
- Print warning for truncated sample
- This resolves https://github.com/iris-hep/idap-200gbps-atlas/issues/140
> Truncate sample name to 128 characters

- servicex/servicex_adapter.py
- tests/test_servicex_adapter.py
In light of using the new Aiohttp module for making async get and post requests, the typical httpx.Response was not working.
Since we were dealing with double context managers e.g
```
async with RetryClient() as client:
async with client.post(url, headers=headers, json=None) as r:
```
Found a way to patch the get request
Decorate the test functions with
`@patch("servicex.servicex_adapter.RetryClient.get")`
Mock response and status
```
get.return_value.__aenter__.return_value.json.return_value = transform_status_response
get.return_value.__aenter__.return_value.status = 200
```
Resources:
https://stackoverflow.com/questions/28850070/python-mocking-a-context-manager
https://blog.sneawo.com/blog/2019/05/22/mock-aiohttp-request-in-unittests/
Optimizations:
``` …
```
> Added Test cases for Servicex_Adapter

- examples/config_definition.yaml
- examples/config_multipe_sample.yaml
- servicex/databinder_models.py
- servicex/func_adl/func_adl_dataset.py
- servicex/models.py
- servicex/servicex_client.py
- tests/conftest.py
- tests/test_databinder.py
- tests/test_dataset_group.py
- tests/test_query_cache.py
- tests/test_servicex_adapter.py
* SignedURLs -> URLs
* Users specify "root-ttree" instead of "root-file" and enum names are changed to "root_ttree".  This involves splitting the types `ResultFormat` and `OutputFormatEnum` : the latter is now used in the `ServiceXSpec` and is translated to a `ResultFormat` when creating the actual request, so that the string sent to the server is still `root-file`. 
Important Note: 
The `ResultFormat` is still what you get back from the server, though, so the cache will continue to handle `root-file` and not `root-ttree`. If at some point we change this string it'll have the side-effect of invalidating caches.
> Change names following #362

- .github/workflows/ci.yaml
- .github/workflows/ci_production.yaml
- pyproject.toml
- servicex/query_core.py
- tests/test_dataset.py
Make `pandas` a dependency only of tests (where it gets used to interpret data), remove references to it from the main library, remove the pandas extra.
Also remove the databinder extra because the package it installs (`nest-asyncio`) is not actually invoked.
> Reduce library dependencies (addresses #432)

- servicex/servicex_client.py
- tests/test_databinder.py
- tests/test_guardlist.py
Instead of storing the original exception in the GuardList, wrap the traceback in a new exception type for better debugging
> Improve GuardList traceback handling

- servicex/query_core.py
- tests/conftest.py
- tests/test_dataset.py
- tests/test_servicex_dataset.py
Address #295 by only verifying that we only list the S3 buckets when we have a cached record if we are trying to get local files when only signed URLs are cached, or vice versa. Fix a number of tests.
> Avoid minio connection if cache is sufficient

- pyproject.toml
- servicex/query_cache.py
TinyDB is not reentrant. Multiple simultaneous requests can result in a corrupt database.
Fixes #361 
Since we need to protect the database from multiple processes, we've used the [filelock](https://py-filelock.readthedocs.io/en/latest/index.html#) library. We create a lock file in the same directory where the cache lives and wrap all interactions with the DB in a context manager that acquires the lock
> Add lock to tinydb

- pyproject.toml
* The default RTD view should also get updated to point to the 'stable' docs.
- c.f. https://servicex.readthedocs.io/en/stable/
> docs: Use ReadTheDocs url for docs

- .github/workflows/ci.yaml
- .github/workflows/docs.yml
* Remove reundant docs build from CI workflow.
* Use 'html' Make target for docs workflow to unify the Makefile experience with the GitHub pages deployment.
Amends PR https://github.com/ssl-hep/ServiceX_frontend/pull/442
> ci: Unify docs build around Makefile

- servicex/minio_adapter.py
Sometimes listing the bucket for an in-progress transformation gives objects that look like directories, not files. These have no file size reported and would raise an exception due to the coercion in the `ResultFile` constructor. Avoid these problematic objects.
> Fix minio handling of buckets in rare cases

- servicex/expandable_progress.py
When there are several in-flight transformations, a failure in one would cause all progress bars to be marked as red (until they completed). This is misleading; transforms that have not failed should still be green. This fix makes only the broken transforms show up as red.
> Fix for colors with multiple progress bars

- docs/conf.py
- pyproject.toml
Resolves #462 
* Add sphinx-copybutton v0.5.2+ to the 'docs' extra.
* Enable sphinx-copybutton support in the Sphinx conf.py.
> docs: Add sphinx-copybutton support

- README.md
- docs/command_line.rst
1. Added badges on the readme page
[![GitHub Actions Status](https://github.com/ssl-hep/ServiceX_frontend/workflows/CI/CD/badge.svg?branch=master)](https://github.com/ssl-hep/ServiceX_frontend/actions)
[![Code Coverage](https://codecov.io/gh/ssl-hep/ServiceX_frontend/graph/badge.svg)](https://codecov.io/gh/ssl-hep/ServiceX_frontend)
[![PyPI version](https://badge.fury.io/py/servicex.svg)](https://badge.fury.io/py/servicex)
[![Supported Python versions](https://img.shields.io/pypi/pyversions/servicex.svg)](https://pypi.org/project/servicex/)
[![Docs](https://readthedocs.org/projects/docs/badge/?version=latest)](https://servicex-frontend.readthedocs.io)
2. Changed heading for command line page
> Badges on readme

- .github/workflows/ci.yaml
- .github/workflows/ci_production.yaml
- .github/workflows/docs.yml
- .github/workflows/pypi.yaml
* Use https://github.com/astral-sh/setup-uv to install and setup uv.
* Remove upgrade of setuptools as the build system uses hatchling.
- Remove upgrade of wheel as the default version is fine.
> ci: Use astral-sh/setup-uv action to setup uv

- docs/command_line.rst
- docs/connect_servicex.rst
- docs/contribute.rst
- docs/index.rst
- docs/query_types.rst
- docs/transform_request.rst
These changes are the result of a quick proofread of the documentation pages. Major changes:
* Fixed up bad `servicex.yaml` file
* Added some `func_adl` information in `query_types`
* Fixed up the contributions guide so it isn't talking about microservices any longer.
And lots of minor changes as well.
> Quick Proofread

- pyproject.toml
- servicex/servicex_adapter.py
- tests/test_servicex_adapter.py
- Add retries (5 times with 3 sec sleep) on the `get` request of `get_transform_status` function
- This can fix the issue #450
> Add retries on the `get` request of `get_transform_status` function

- servicex/query_core.py
When the user submits many requests, sometimes the transform status returns only partial number of files.
After subsequent polling, the correct number of files are returned. However, the download progress bar wasn't geting updated.
Inside the `transform_status_listener` added the update logic for download progress bar.
> Update the download progress bar (both unsigned and dowload) when initial transform request doesn't return all files

- servicex/minio_adapter.py
We should not terminate a request because of a single S3 poll error. Use tenacity to retry a couple of times
> Add retries for s3 interactions with tenacity

- .github/workflows/ci_production.yaml
* `examples/Uproot_UprootRaw_Dict.py` doesn't exist but [`examples/UprootRaw_Dict.py`](https://github.com/ssl-hep/ServiceX_frontend/blob/048723250e6bf0e2734c6d12980cf9a1dc6ff4bc/examples/UprootRaw_Dict.py) does.
> ci: Fix file name error

- servicex/databinder_models.py
- servicex/dataset_identifier.py
- tests/test_databinder.py
Resolve #467 by rejecting setting `NFiles=0` (or `num_files=0`) during `Sample` specification
> Prevent user passing nfiles=0 when creating a sample

- servicex/query_cache.py
- servicex/query_core.py
- tests/test_query_cache.py
- tests/test_servicex_dataset.py
Resolve #375 
```
cached_record = (
self.cache.get_transform_by_hash(sx_request_hash)   # this raises exception when 2 records are present
if not self.ignore_cache
else None
)
```
When the user submits a transform without `ignore-cache` -> records are inserted as expected
When the user submits same transform with `ignore-cache` -> a NEW record is still created (tiny db has no unique value contraints)
When the user submits same tranform without `ignore-cache` -> 2 records are present hence raises exception
When the user submits a query and selects ignore_cache -
Check if we have a previous hash already present and if present delete that record since we are going to run the transform again.
> Cache Collision when the user ignores the cache and hash is present in the db Fix #375

- docs/datasets.rst
- docs/index.rst
- docs/transform_request.rst
- pyproject.toml
- servicex/dataset/__init__.py
- servicex/dataset_identifier.py
- tests/test_databinder.py
- tests/test_servicex_dataset.py
Add a class to encapsulate an XRootD dataset request (resolve #477)
> Add XRootD dataset identifier class

- servicex/query_cache.py
- tests/test_query_cache.py
Problem #417 
Fixes #417 
When a sample has many files which have the same details except different sample names, multiple records were created for the same request (same hash). Due to the async nature of the requests, the files are downloaded asynchronously and hash value was also inserted in the db.
Fix
Added a condition in the insert statement of the cache where it only inserts if the hash value is not previously present. The locks previously installed eliminates the race condition.
> Multiple samples submitted together updates the database only once #417

- servicex/models.py
- tests/test_query_cache.py
Resolves #396 
Problem:
When submitting multiple requests with same file names but different order different hash were computed hence recomputing results.
Fix:
Simply sort the file names before the hash is calculated
> Caching behavior of permutation fix #396

- servicex/servicex_adapter.py
- tests/test_servicex_adapter.py
Resolves #473:
* if an auth token is within 60 seconds of expiry, renew it before proceeding with request;
* if a transformation status query returns an auth error, attempt a retry with an updated token;
* add better handling of other error codes when querying transformation status.
> Better handling of tokens near expiry

- README.md
* Distinguish between the 'user' docs being the default 'stable' view of ReadThe Docs and the 'developer' docs being the 'latest' view, which is built from the latest commit on the default branch.
> docs: Note that ReadTheDocs is the user docs

- docs/transform_request.rst
- servicex/__init__.py
Resolve #449 by exposing `DeliveryEnum` as `servicex.Delivery` (`OutputFormat` was already added). Add documentation.
> Expose `Delivery` enum

- servicex/query_cache.py
- servicex/query_core.py
- tests/test_dataset.py
- tests/test_query_cache.py
Resolves https://github.com/ssl-hep/ServiceX_frontend/issues/468
Problem
When the client submits the request but encounters client failure, there is no way of resuming the transforms from the last point. The client is forced to rerun the request which triggers the backend again.
Fix
Single Database instance -- Added flag
This PR fixes the broken client problem. The client will be able to resume the request from the last point. Given the client submits the same request again (important since the request hash is calculated and compared with any pending requests)
> Single Database instance -- Resume request when client fails fixes #468 

- servicex/query_core.py
- servicex/servicex_client.py
Change `deliver()` to fail for a sample (by default) if any files fail. Can be disabled by passing `fail_if_incomplete=False`.
> New argument `fail_if_incomplete` to raise an exception if any files fail

- servicex/expandable_progress.py
- servicex/query_core.py
- tests/test_expandable_progress.py
Hopefully resolves #475 (though the issue is generally hard to reproduce these days). In any case doesn't do any harm.
> Final refresh of progress bars when transform is complete

- docs/command_line.rst
- servicex/app/datasets.py
- servicex/models.py
- servicex/servicex_adapter.py
- servicex/servicex_client.py
- tests/test_servicex_adapter.py
- tests/test_servicex_client.py
This PR depends on the [Service PR 907](https://github.com/ssl-hep/ServiceX/pull/907)
Add a new command to the CLI
```bash
servicex datasets list -b testing1
```
Also accepts an optional argument `--did-finder` to filter on a specific DID Finder such as `rucio` or `user`.
```bash
% servicex datasets list -b testing2 --did-finder rucio                       
ServiceX Datasets                                                                               
┏━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓
┃ ID ┃ Name                                                                                                                ┃ Files ┃ Size    ┃ Status   ┃ Created …
```
> Add cli command to list datasets

- servicex/databinder_models.py
- servicex/models.py
- servicex/uproot_raw/uproot_raw.py
Pydantic model classes had completely unhelpful docstrings. This is a design decision by the Pydantic folks, but they provide a workaround (the ability to change the `__doc__` attribute via a post-initialization hook - see https://github.com/pydantic/pydantic/issues/638#issuecomment-1557258506). This is implemented. Resolves #303
> Improve docstrings for Pydantic models

- servicex/dataset_identifier.py
- tests/test_dataset_identifier.py
Resolves #31. `RucioDatasetIdentifier` will throw an exception if a namespace isn't specified.
> Require namespace in Rucio DIDs

- servicex/query_core.py
- servicex/servicex_adapter.py
- tests/test_servicex_adapter.py
Resolve #502. Do not assume that error responses from the backend are JSON except for specific HTTP codes.
> Improve handling of error codes from server

- tests/test_config.py
Test to make sure that #210 (which is already fixed) stays fixed
> Add a test to make sure that we raise an exception if there is no servicex config file

- docs/command_line.rst
- servicex/app/datasets.py
- servicex/models.py
- servicex/servicex_adapter.py
- servicex/servicex_client.py
- tests/test_servicex_adapter.py
- tests/test_servicex_client.py
User's can't delete a dataset from the cache. They also can't see the details of a DID to debug
Add some new commands to the CLI
```bash
servicex datasets get -b testing2 15
```
This gets back the details of Dataset ID 15... 
```
Dataset ID 15                                                                        
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Paths                                                                                                                                                     ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ …
```
> Delete Dataset From CLI

- servicex/dataset_group.py
- servicex/servicex_adapter.py
- tests/test_dataset_group.py
Resolves #506. Get authentication before actually doing submission, so we can raise an exception early and not hide it in the `GuardList` in the return value of `deliver`.
> Do a preflight authentication call

- docs/conf.py
I don't see a reason why user needs to see source code of documentation readthedoc pages. It's a bit annoying place by default, so I would like to remove it 😄 
Current
New
> Remove view source code button from documentation

- pyproject.toml
- servicex/app/cli_options.py
- tests/test_app.py
Use pytest-console-scripts to allow us to test the `servicex` CLI with patches to backend code. This is not at all intended to be comprehensive, but to establish a framework. Starts to address #351
> Introduce example of app testing with patches

- .pre-commit-config.yaml
Add hooks for precommit + some basic checks (and run flake8)
> Add precommit hooks

- servicex/servicex_adapter.py
- tests/test_servicex_adapter.py
The delete command in the dataset cli tests for a True return value from the ServiceXAdapter. Unfortunately, the `delete_dataset` method doesn't return anything.
Add a check for the `stale` property in the value returned from the server and return that from the method
> Check for return value on dataset delete

- servicex/query_core.py
- tests/test_dataset.py
If a transform task completed while the download polling was going on, we might miss some outstanding files to download. Do not terminate the polling loop now until all files are seen in the object store.
> Avoid race condition between status monitoring and download tasks

- docs/command_line.rst
- servicex/app/cli_options.py
- servicex/app/codegen.py
- servicex/app/datasets.py
- servicex/app/transforms.py
This pull request removes the `--url` option from various CLI commands and updates the documentation accordingly. The changes ensure that the client now relies solely on the `--backend` option to determine the ServiceX server.
The --url option was never used. It's easy enough to just add a new entry to .servicex and this option was cluttering up the code
Key changes include:
* [`docs/command_line.rst`](diffhunk://#diff-c8aa0277057c29741b54e77dc385a622dcee6a8db3d16516eb4e1fb402becd99L16-R20): Removed the `-u`/`--url` option from the list of common command line arguments and updated the description to reflect that only the `--backend` option is required.
* [`servicex/app/cli_options.py`](diffhunk://#diff-3cf1e67d032b1142f64d604d40779cd05c81015b8f2a43c8828a99139a48e649L31): Removed the …
> Eliminate unnecessary URL options from the command line.

- docs/query_types.rst
Moved xaod_usage docs over to iris-hep from Gordon's git hub. Needed to update the link in the service x frontend docs to reflect these changes.
> Updated xaod_usage documentation URL in ServiceX_frontend docs.

- pyproject.toml
Resolves #540 
* ruamel-yaml v0.18.7 has a breaking API change relative to v0.18.6. Until this can be fixed, introduce a short lived version cap.
- c.f. https://pypi.org/project/ruamel.yaml/0.18.7/ c.f. https://sourceforge.net/p/ruamel-yaml/code/ci/0.18.7/tree/
> build:  Restrict ruamel-yaml to v0.18.6 or older

- docs/command_line.rst
- servicex/app/__init__.py
- servicex/app/cache.py
- servicex/app/datasets.py
- servicex/app/main.py
- servicex/app/transforms.py
- servicex/databinder_models.py
- servicex/servicex_adapter.py
- servicex/servicex_client.py
- tests/app/test_app.py
- tests/app/test_codegen.py
- tests/app/test_datasets.py
- tests/app/test_transforms.py
- tests/test_servicex_adapter.py
- tests/test_servicex_client.py
This pull request introduces several new features and improvements to the ServiceX CLI. The most notable changes include the addition of new commands, enhancements to the output formatting, and the implementation of new functionalities for managing transforms. Also completed the unit tests for the CLI code. Below is a summary of the most important changes:
* Added `deliver` command to submit a YAML configuration file to the ServiceX backend and print the resulting file paths. (`docs/command_line.rst`, `servicex/app/main.py`) [[1]](diffhunk://#diff-c8aa0277057c29741b54e77dc385a622dcee6a8db3d16516eb4e1fb402becd99R23-R29) [[2]](diffhunk://#diff-45693d9f0af917dbdeafd6fb97e3f240a375ff3cc5e1b33b59f813e6131d196aR68-R81)
* Added `cancel` command to cancel a running transform. …
> Cleanup cli

- .github/workflows/ci.yaml
- pyproject.toml
- servicex/query_core.py
Fixes `pre-commit` being missing when building development containers
> Add pre-commit to developer extras [DROPS PYTHON 3.8 SUPPORT]

- .github/workflows/pypi.yaml
* Avoid metadata regression in older unsupported releases.
- c.f. https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.12.3
Context: This hit the `v3.1.0` release with
```
Run pypa/gh-action-pypi-publish@v1.8.14
/usr/bin/docker run --name e5ae9006f954b2ebae5758a4983adcd_3327b8 --label 034110 --workdir /github/workspace --rm -e "pythonLocation" -e "PKG_CONFIG_PATH" -e "Python_ROOT_DIR" -e "Python2_ROOT_DIR" -e "Python3_ROOT_DIR" -e "LD_LIBRARY_PATH" -e "UV_CACHE_DIR" -e "RELEASE_VERSION" -e "INPUT_PRINT-HASH" -e "INPUT_USER" -e "INPUT_PASSWORD" -e "INPUT_REPOSITORY-URL" -e "INPUT_REPOSITORY_URL" -e "INPUT_PACKAGES-DIR" -e "INPUT_PACKAGES_DIR" -e "INPUT_VERIFY-METADATA" -e "INPUT_VERIFY_METADATA" -e "INPUT_SKIP-EXISTING" -e "INPUT_SKIP_EXISTING" -e "INPUT_VERBOSE" -e …
```
> ci: Update pypa/gh-action-pypi-publish to v1.12.3

- .devcontainer/Dockerfile
Previous PR #549 unintentionally changed the devcontainer `Dockerfile` to pull from a non-existent tag (0-3.13). I have changed it to 1-3.13 .
> Fix devcontainer python image base

- .github/dependabot.yml
- .github/workflows/ci.yaml
- .github/workflows/ci_production.yaml
- .github/workflows/docs.yml
- .github/workflows/pypi.yaml
* Enable weekly checks for updates to GitHub Actions in use with Dependabot. Group the updates into a single PR to avoid PR noise.
* Update GitHub Actions to latest versions:
- actions/checkout v3 -> v4
- actions/setup-python v4 -> v5
- astral-sh/setup-uv v3 -> v5
- codecov/codecov-action v3 -> v5
* Remove '3.0_develop' branch as trigger for docs workflow, as it no longer exists.
> ci: Add Dependabot updates for GitHub Actions

- servicex/query_core.py
Keep the minio polling interval but do nothing if the current transform status does not indicate more files than the last time we looked in S3.
> Don't poll S3 unless we have reason to think there are new files available

- servicex/__init__.py
- servicex/dataset_group.py
- servicex/expandable_progress.py
- servicex/servicex_client.py
- tests/test_databinder.py
- tests/test_expandable_progress.py
* Fix issues in ExpandableProgress that broke summary bar
* Pass necessary arguments down from deliver()
* Introduce enum class that lets user choose default display (all bars), compact display (only the total progress), or no progress bars at all
> Give users options to condense or eliminate progress bars

- servicex/app/cache.py
- servicex/app/datasets.py
- servicex/app/main.py
- servicex/app/transforms.py
- tests/test_query_cache.py
Address #525 - mostly clean up function calls in argument defaults in CLI app. Bugbear has opinions about "bad code smell" and in this case the warnings are pretty harmless (these are functions that only get called once) but still better to have a clean report.
> Clean up bugbear issues (address #525)

- servicex/minio_adapter.py
- tests/test_minio_adapter.py
Downloading large datasets from Ceph object store can result in timeout exceptions.
Explicitly set the timeout on the minio fget to 10 minutes.
> Increase minio fget timeout

- pyproject.toml
- servicex/models.py
Neither `tree-name` nor `image` should be specified in ServiceX requests. The former does nothing anyway and the latter is a security risk. In any case the frontend v3 API doesn't provide any way for users to set them.
> Remove obsolete fields in transform requests

- pyproject.toml
- servicex/minio_adapter.py
- servicex/query_core.py
- servicex/servicex_client.py
- tests/conftest.py
- tests/test_databinder.py
- tests/test_minio_adapter.py
Fixes #571 . `aioboto3` has better built-in error detection and retry support than `minio`.
Merge after #573
> Switch S3 client to boto3

- .github/workflows/ci.yaml
There is a conflict in setting up Python versions with 3.13t if we use both the setup-python and setup-uv actions. Do only the latter. (This PR does not itself bring in 3.13t, that has conflicts with dependencies, specifically aiohttp https://github.com/aio-libs/aiohttp/discussions/10467 .)
> Use uv to set up python version in tests

- servicex/minio_adapter.py
- servicex/servicex_client.py
- tests/test_minio_adapter.py
Replace #573 by using the native concurrency handling of the boto3 libraries. Up the default concurrency to 10 (matches the default in the library).
> Upgrade local download concurrency control to use aioboto3's built-in handling

- .github/workflows/pypi.yaml
- pyproject.toml
I added a couple of steps in `pypi.yml` to commit the version bump when a release is created.
I also changed the version tag replacement using `sed`. 
There was an extra white space being introduced. This would cause the reggex search to fail on the next release event.
This should fix the doc building issue (currently showing the wrong release tag) automaticaly for next releases. 
This garantees `pyproject.toml` in master is consistent with the distributed package tag. 
I also manualy set the version to 3.1.1 since that release is published. 
--------------------------------------------------------------------------------
Tested with pre-releases on the feat/version-bump-gha branch, and the github bot correctly comits the version bump.
> Adding steps to pypi workflow - bot commit version bump

- .github/workflows/ci.yaml
Use a venv for uv package installation instead of using the system installation.
> Fix CI for astral-sh/setup-uv 6

- docs/analysis_tools.md
- docs/index.rst
Added a section to the documentation about the parallel package with extra tools. 
The section does not go into details and points to the GH repo and the documentation.
I investigated the functionalities of the `intersphinx` extension. They could be useful if the second package grows and information has to be added more extensively to the client's doc. For now just pointing to links is enough. 
I placed this section after the CLI module.
> Adding section to analysis utils package

- servicex/minio_adapter.py
- servicex/query_core.py
- tests/app/test_datasets.py
- tests/test_minio_adapter.py
- tests/test_servicex_dataset.py
I had misunderstood the concurrency limit in the boto3 configuration as a global limit, but it is only a limit on the number of parallel downloads for each individual download request. Therefore we could still be spawning a huge number of simultaneous S3 connections.
This PR puts semaphores back to limit the number of distinct simultaneous connections. It also tries to reduce the total number of connections made:
* it reuses metadata obtained in the bucket listing,
* it uses a lower level part of the library that means that fewer requests are made.
The new magic numbers are
* maximum 5 simultaneous bucket listings
* maximum 10 distinct files being downloaded simultaneously (configurable)
* maximum 5 download streams per file (internal boto configuration)
> Add back concurrency semaphore

- servicex/servicex_client.py
A number of functions (unintentionally, I think) returned coroutines instead of taking action. Fixed (though this is technically API breaking). Tests no longer raise warnings about non-awaited coroutines.
> Fix some methods with undocumented coroutine returns

- tests/test_minio_adapter.py
- tests/test_servicex_adapter.py
There were some odd test failures on Windows. Identified a few issues with the mocking environments:
* needed to patch the token renewal path for an expired token
* S3 mocker actually tore down bucket state between tests and on Windows we would issue a delete command when the object was already gone
> Fix test issues on Windows

- docs/query_types.rst
- servicex/uproot_raw/uproot_raw.py
Documentation and a smal tweak for client support for https://github.com/ssl-hep/ServiceX/pull/1054 .
> Documentation and client support for changes to the uproot-raw axis default

- servicex/servicex_adapter.py
- tests/test_servicex_adapter.py
We get an output database record for each input file, regardless of whether the transformation was successful or not. Check the transform success so we don't try to download nonexistent files.
> Do not try to download failed files

- .github/workflows/pypi.yaml
This is causing a failure in the build since branch protection rules prevent a direct push to master branch.
Reverting this for now and need to investigate a way to make this work with the branch protection bypass rules
> Revert the commit of version to pyproject.toml

- servicex/query_cache.py
- tests/test_query_cache.py
If `servicex cache list` is called while jobs are listed in the cache in the SUBMITTED state, it will crash since the stored documents are not proper `TransformedResults`. Exclude these requests from the list.
> Avoid trying to interpret cached transformations in the SUBMITTED state

- pyproject.toml
We are currently using `hatch` as a build system.
This change allows the user to execute tests in an isolated environment directly from the command line:
```
hatch run test:test
```
The old way, where test packages are only set as optional dependencies, requires the user to manually set the environments packages prior to executing tests:
```
pip install -e ".[test]"
hatch run python -m pytest
pip install -e .
```
> add pyproject hatch test environment

- tests/test_servicex_adapter.py
One test would occasionally fail because the token "validity time" was set up when the module was imported, and by the time the test was actually executed the validity interval might have passed. Extend the interval so as to make this much less likely.
> Extend fake token validity

- servicex/servicex_adapter.py
- servicex/servicex_client.py
- tests/test_databinder.py
- tests/test_default_endpoint.py
- tests/test_servicex_adapter.py
- tests/test_servicex_dataset.py
It seems that `make_sync` can have bad interactions with other code that sets up event loops and should really only be used for top-level interfaces. Change a couple of places to use async versions of functions, run via `asyncio`.
This is needed to fix the failures in the production tests.
> Better handoff to async code

- servicex/servicex_adapter.py
httpx has much shorter timeouts than aiohttp did, and large submissions can exceed the default 5s limits. Raise this for submissions to be much closer to aiohttpx.
> Extend timeout for httpx `put` in submission

- pyproject.toml
Modify `pyproject.toml` to support coverage options closer aligned to the GitHub build steps:
```[tool.hatch.envs.test.scripts]
test = "pytest {args}"
cov = "coverage run --source servicex/ -m pytest tests && coverage report"
cov-html = "coverage run --source servicex/ -m pytest tests && coverage html"```
> change coverage options to match github build steps
