servicex/servicex.py, setup.py
function get_data now passes input data_type to get_data_async on line 244.
=> Bugfix for data_type

scripts/run_test.py, servicex/__init__.py, servicex/minio_adaptor.py, servicex/servicex.py, servicex/servicex_adaptor.py, servicex/utils.py, setup.py, tests/test_servicex.py, tests/test_servicex_adaptor.py, tests/test_utils.py, tests/utils_for_testing.py
An attempt to clean up the logic
=> Linearize the request sequence

servicex/minio_adaptor.py, servicex/servicex.py, tests/conftest.py, tests/test_minio_adaptor.py, tests/test_servicex.py
- Added a MinioAdaptorFactory that will create a MinioAdaptor
- Added feedback code to grab minio adaptor info from the transform status
fixes #70
=> ServiceX minio endpoint return

.vscode/settings.json, README.md
Describe the new workflow for doing development work
Fixes #89
=> Prove we can work with this new branch structure

setup.py
=> Minor update to qastle version number

README.md, servicex/ConfigSettings.py
With this PR, the frontend will search for config information in a `servicex.yaml`, `servicex.yml`, and `.servicex` file.
=> Get config information from servicex.yaml and servicex.yml and .servicex files

setup.py
Allow `pyarrow` 2.0 to be installed
=> Allow pyarrow v1 or 2

servicex/servicex.py
=> Fix incorrect usage of MinioAdaptorFactory call

README.md
=> Fix up name issue on pypi

servicex/config_default.yaml
=> Add the CMS Run1 default backend data type

servicex/servicex.py, servicex/servicexabc.py, servicex/utils.py, tests/test_servicex.py, tests/test_utils.py
* If a specified transform title is given, then use that as a title
* Truncate the resulting title string if it is too long
* Make sure that the Download progress bar is given a real title (in case the processing one disappears)
* Properly use the notebook version of tqdm when running under vscode
Fixes #195
Fixes #190
Fixes #186
=> tqdm UI Fixes

servicex/servicexabc.py, servicex/utils.py, tests/test_servicex.py, tests/test_utils.py
* Adds a `dataset_as_name` property to the `ServiceXDataset` which will return a "human" version of the dataset name
=> Return a datset name

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, tests/test_utils.py
This should make it possibel to run all tests from "go" in code spaces on github
=> Getting a codespaces setup working

.github/workflows/ci.yaml, setup.py
* Update setup, etc., to run under python 3.10
=> Update to python 3.10

tests/test_data_conversions.py
Type fixes in test_data_conversions.py
=> Ignoring type warnings in test_data_conversions.py

.github/workflows/pypi.yaml
Fixes incorrect pypi regression recently introduced.
=> Fix up to use proper name of the token

servicex_client/func_adl_dataset.py, servicex_client/servicex_client.py, tests/test_servicex_dataset.py
* Support typing for func_adl datasets
* Minor spelling, type, formatting fixes
=> Typed FuncADL Datasets

pyproject.toml, servicex_client/dataset.py, servicex_client/dataset_group.py, servicex_client/servicex_client.py
* Use the library `make_it_sync` to support various environments (like command line, jupyter, etc.).
=> Robust sync async routines

servicex_client/servicex_client.py
* Recover from an incorrect rebasing (I got basted!)
=> Fix removed type info

servicex/app/cache.py, servicex/app/main.py, servicex/app/transforms.py
The help messages for the CLI are incomplete and some still reference the old project this code was based on.
Fixes #290
=> Clean up typer help messages

servicex/func_adl/func_adl_dataset.py
The initial implementation would break for more complicated selects.
=> Find eventdataset

examples/dataset_group.py, examples/single_file_uproot.py, examples/xAODDataset.py, servicex/app/codegen.py, servicex/query_cache.py, servicex/servicex_client.py
This commit adds functionality to cache the code generators for offline processing.
=> Add a cache for the code generators

servicex/dataset.py, servicex/dataset_group.py, servicex/expandable_progress.py, tests/test_dataset.py, tests/test_expandable_progress.py
=> Compress Progress bars to a single bar for dataset groups

examples/bigger_uproot.py, examples/config_databinder.yaml, examples/databinder.py, examples/databinder_python_script.py, examples/dataset_group.py, examples/python_codegen.py, examples/single_file_uproot.py, examples/xAODDataset.py
Update examples for servicex backend v1.3.2
=> Update examples for servicex backend v1.3.2

examples/config_databinder_func_adl.yaml, servicex/__init__.py, servicex/databinder_models.py, servicex/servicex_client.py
- Mostly clear from the commit messages
- Changes enable the notebook example for ACAT 2024 poster
=> Changes in the cosmetics of databinder integration

.github/workflows/ci.yaml
Only do coverage in the servicex/ directory
=> Restrict coverage stats

docs/conf.py, docs/dataset.rst, docs/transformer_matrix.md, docs/transformer_matrix.rst, pyproject.toml
Add a matrix of query languages to data formats, document uproot-raw
=> Add some documentation on codegens

servicex/uproot_raw/uproot_raw.py
Otherwise Pydantic 2.7 is unhappy
=> Defaults for uproot-raw model

servicex/models.py
Add an additional status that can be returned by the server (if not handled the client can die with an exception)
=> Add "Pending lookup" status to enum

.readthedocs.yaml, docs/requirements.txt
Added the .readthedocs.yaml and requirements.txt file for RTD
=> Readthedocs deployement .yaml and requirements.txt files

.github/workflows/ci-production.yaml, .github/workflows/ci_production.yaml
Add more examples, rename yaml for consistency
=> Update production CI

servicex/servicex_adapter.py
- Set timeout in the `ExponentialRetry` than client methods such as `post`
=> Fix timeout configuration

pyproject.toml
Prepare for 3.0.1 release with an alpha
=> Bump release version to 3.0.1-alpha.1

docs/about.rst
- A table of presentations on the client only (or major topic is client) for users who want to know more about the client
- Response to the issue by @matthewfeickert - https://github.com/ssl-hep/ServiceX_frontend/issues/465
=> Update About page of documentation

.github/workflows/ci_production.yaml
Make it clearer what is going on in test
The endpoint will be printed in the test. As it is a secret, to get it to output it is encoded via `xxd -ps`;  it can be de-encoded by `xxd -r -ps`.
=> Update ci_production.yaml to print target of test

.github/workflows/ci.yaml
Fix codecov / pytest interaction
=> Update codecov execution

servicex/dataset_group.py, tests/conftest.py, tests/test_databinder.py
=> Pushdown progress bar spec & fix tests

docs/query_types.rst, servicex/uproot_raw/uproot_raw.py
Frontend support for https://github.com/ssl-hep/ServiceX/pull/1027
=> Support fail_on_missing_trees option

docs/transform_request.rst, docs/transformer_matrix.md, servicex/databinder_models.py, servicex/models.py, tests/test_databinder.py
=> RNTuple support

servicex/app/datasets.py, tests/app/test_datasets.py
PR #604 broke a few functions in the CLI. Fix.
=> Some things did expect async get_datasets etc.
